### ISSUE TITLE
mobile menu does not work with bootstrap Version V5

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/directory-starter#19]
https://secure.helpscout.net/conversation/2182669382/41415/
https://secure.helpscout.net/conversation/2472052516/50562?folderId=3812058

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2517812411/52312/
https://secure.helpscout.net/conversation/2525276775/52613?folderId=3812058

**Comment by kprajapatii** [comment]
ticket: https://secure.helpscout.net/conversation/2609042112/56531/

The same is happening on my dev site https://ppldb.com/nick/ (the dev site has only Supreme + Starter themes and geo plugins)

**Comment by kprajapatii** [comment]
Fixed in Directory Starter & Supreme Directory both themes.

https://github.com/AyeCode/directory-starter/pull/21/commits/273acb1e4a17a7418089156a1541a0c17f5b4045
https://github.com/AyeCode/supreme-directory/pull/78/commits/3e982b49f61ad48a37458bdfd6b5bc27db957cb9
