### ISSUE TITLE
BP Registration page loads sidebar even if set to full width

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/directory-starter#3]
can be seen here:
https://ppldb.com/v2/bp-register/

reported here
https://wpgeodirectory.com/support/topic/upgrade-to-gdv2/page/3/#post-462987

@kprajapatii

**Comment by kprajapatii** [comment]
This is not DS issue, it happens with WP Twenty Twelve theme also. 

I have fixed this via snippet. See https://wpgeodirectory.com/support/topic/upgrade-to-gdv2/page/3/#post-463684
